import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const deaconBlack = localFont({
  src: "./fonts/Deacon-black.woff",
  variable: "--font-deacon-black",
  weight: "900",
});
const deaconBold = localFont({
  src: "./fonts/Deacon-bold.woff",
  variable: "--font-deacon-bold",
  weight: "700",
});
const GraphikMedium = localFont({
  src: "./fonts/GraphikMedium.woff",
  variable: "--font-graphik-medium",
  weight: "500",
});
const GraphikSemibold = localFont({
  src: "./fonts/GraphikSemibold.woff",
  variable: "--font-graphik-semibold",
  weight: "600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${deaconBlack.variable} ${deaconBold.variable} ${GraphikMedium.variable} ${GraphikSemibold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
